package universidadejemplo.Vistas;


/**
 * louisinette
 */
public class CargaNotas extends javax.swing.JInternalFrame {


    public CargaNotas() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLCargaNotas = new javax.swing.JLabel();
        jComboBListAlumCargaNotas = new javax.swing.JComboBox();
        jLSelectAlumn = new javax.swing.JLabel();
        jLSelectAlumn1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCargaNotas = new javax.swing.JTable();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalirCargaNotas = new javax.swing.JButton();
        jLbFondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 110, 232));

        jPanel1.setBackground(getBackground());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/&Images/logo-ulp.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 304, -1));

        jLCargaNotas.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLCargaNotas.setForeground(java.awt.Color.orange);
        jLCargaNotas.setText("Carga de Notas");
        jPanel1.add(jLCargaNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        jComboBListAlumCargaNotas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jComboBListAlumCargaNotas.setToolTipText("");
        jPanel1.add(jComboBListAlumCargaNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 338, 461, 40));

        jLSelectAlumn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLSelectAlumn.setForeground(new java.awt.Color(255, 255, 255));
        jLSelectAlumn.setText("Seleccione un alumno:");
        jPanel1.add(jLSelectAlumn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLSelectAlumn1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLSelectAlumn1.setForeground(new java.awt.Color(255, 255, 255));
        jLSelectAlumn1.setText("A continuación ud. podra modificar la Nota del alumno seleccionado:");
        jPanel1.add(jLSelectAlumn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 425, -1, -1));

        jTableCargaNotas.setAutoCreateRowSorter(true);
        jTableCargaNotas.setBackground(new java.awt.Color(255, 255, 102));
        jTableCargaNotas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTableCargaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCargaNotas.setGridColor(java.awt.Color.orange);
        jTableCargaNotas.setRowHeight(24);
        jScrollPane1.setViewportView(jTableCargaNotas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 558, 140));

        jButtonGuardar.setBackground(java.awt.Color.orange);
        jButtonGuardar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 680, -1, -1));

        jButtonSalirCargaNotas.setBackground(java.awt.Color.orange);
        jButtonSalirCargaNotas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonSalirCargaNotas.setText("Salir");
        jButtonSalirCargaNotas.setToolTipText("");
        jPanel1.add(jButtonSalirCargaNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 680, -1, -1));

        jLbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/&Images/bckg3.jpg"))); // NOI18N
        jLbFondo.setDisabledIcon(null);
        jPanel1.add(jLbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


 
   public static void main(String args[]) {
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonGuardar;
    public javax.swing.JButton jButtonSalirCargaNotas;
    public javax.swing.JComboBox jComboBListAlumCargaNotas;
    private javax.swing.JLabel jLCargaNotas;
    private javax.swing.JLabel jLSelectAlumn;
    private javax.swing.JLabel jLSelectAlumn1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLbFondo;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableCargaNotas;
    // End of variables declaration//GEN-END:variables

}