package universidadejemplo.Vistas;


/**
 * louisinette
 */
public class CargaNotas extends javax.swing.JInternalFrame {


    public CargaNotas() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLCargaNotas = new javax.swing.JLabel();
        jComboBListAlumCargaNotas = new javax.swing.JComboBox();
        jLSelectAlumn = new javax.swing.JLabel();
        jLSelectAlumn1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCargaNotas = new javax.swing.JTable();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalirCargaNotas = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 110, 232));

        jPanel1.setBackground(getBackground());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/&Images/logo-ulp.png"))); // NOI18N

        jLCargaNotas.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLCargaNotas.setForeground(java.awt.Color.orange);
        jLCargaNotas.setText("Carga de Notas");

        jComboBListAlumCargaNotas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLSelectAlumn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLSelectAlumn.setText("Seleccione un alumno:");

        jLSelectAlumn1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLSelectAlumn1.setText("A continuación ud. podra modificar la Nota del alumno seleccionado:");

        jTableCargaNotas.setAutoCreateRowSorter(true);
        jTableCargaNotas.setBackground(new java.awt.Color(255, 255, 102));
        jTableCargaNotas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTableCargaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCargaNotas.setGridColor(java.awt.Color.orange);
        jTableCargaNotas.setRowHeight(24);
        jScrollPane1.setViewportView(jTableCargaNotas);

        jButtonGuardar.setBackground(java.awt.Color.orange);
        jButtonGuardar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonGuardar.setText("Guardar");

        jButtonSalirCargaNotas.setBackground(java.awt.Color.orange);
        jButtonSalirCargaNotas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonSalirCargaNotas.setText("Salir");
        jButtonSalirCargaNotas.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLSelectAlumn1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLCargaNotas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jButtonGuardar)
                        .addGap(103, 103, 103)
                        .addComponent(jButtonSalirCargaNotas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLSelectAlumn)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBListAlumCargaNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLCargaNotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSelectAlumn)
                    .addComponent(jComboBListAlumCargaNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jLSelectAlumn1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonSalirCargaNotas))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


 
   public static void main(String args[]) {
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonGuardar;
    public javax.swing.JButton jButtonSalirCargaNotas;
    public javax.swing.JComboBox jComboBListAlumCargaNotas;
    private javax.swing.JLabel jLCargaNotas;
    private javax.swing.JLabel jLSelectAlumn;
    private javax.swing.JLabel jLSelectAlumn1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableCargaNotas;
    // End of variables declaration//GEN-END:variables

}