/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadejemplo.Vistas;

/**
 *
 * @author PC1
 */
public class GestionMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionMateria
     */
    public GestionMateria() {
        initComponents();
   
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxCodigo = new javax.swing.JTextField();
        jbtBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtxNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxAño = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jchEstado = new javax.swing.JRadioButton();
        jbtSalir = new javax.swing.JButton();
        jbtNuevo = new javax.swing.JButton();
        jbtEliminar = new javax.swing.JButton();
        jbtGuardar = new javax.swing.JButton();
        jLbFondo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Materia");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel2.setText("Codigo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 79, -1, -1));

        jtxCodigo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jPanel1.add(jtxCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 74, 128, -1));

        jbtBuscar.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jbtBuscar.setText("Buscar");
        jPanel1.add(jbtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 71, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 118, -1, -1));

        jtxNombre.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jPanel1.add(jtxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 113, 281, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel4.setText("Año:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 159, -1, -1));

        jtxAño.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jPanel1.add(jtxAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 154, 96, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel5.setText("Estado:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 199, -1, -1));
        jPanel1.add(jchEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 199, -1, -1));

        jbtSalir.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jbtSalir.setText("Salir");
        jPanel1.add(jbtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        jbtNuevo.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jbtNuevo.setText("Nuevo");
        jPanel1.add(jbtNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jbtEliminar.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jbtEliminar.setText("Eliminar");
        jPanel1.add(jbtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jbtGuardar.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jbtGuardar.setText("Guardar");
        jPanel1.add(jbtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLbFondo.setText("jLabel6");
        jPanel1.add(jLbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLbFondo;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtBuscar;
    public javax.swing.JButton jbtEliminar;
    public javax.swing.JButton jbtGuardar;
    public javax.swing.JButton jbtNuevo;
    public javax.swing.JButton jbtSalir;
    public javax.swing.JRadioButton jchEstado;
    public javax.swing.JTextField jtxAño;
    public javax.swing.JTextField jtxCodigo;
    public javax.swing.JTextField jtxNombre;
    // End of variables declaration//GEN-END:variables
}
