package universidadejemplo.Vistas;

import javax.swing.table.DefaultTableModel;
import universidadejemplo.Entidades.Alumno;

/**
 *
 * @author PC1 Gimenez Diego
 */
public class Inscripciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inscripciones
     */
    public Inscripciones() {
        initComponents();
        setTitle("Inscripciones");
    }

    private static void addColumn(String id) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtInscribir = new javax.swing.JButton();
        jbtAnularInscripcion = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();
        jRadioButtonMateriasInscriptas = new javax.swing.JRadioButton();
        jRadioButtonMateriasNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBListAlum = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(102, 0, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulario de Inscripciones");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccione un alumno:");

        jbtInscribir.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jbtInscribir.setForeground(new java.awt.Color(0, 204, 102));
        jbtInscribir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/&IconButtons/Inscribir.png"))); // NOI18N
        jbtInscribir.setText("Inscribir");
        jbtInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtInscribirActionPerformed(evt);
            }
        });

        jbtAnularInscripcion.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jbtAnularInscripcion.setForeground(new java.awt.Color(102, 0, 102));
        jbtAnularInscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/&IconButtons/inactivo.png"))); // NOI18N
        jbtAnularInscripcion.setText("Anular inscripcion");

        jbtSalir.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jbtSalir.setAlignmentY(0.0F);
        jbtSalir.setContentAreaFilled(false);
        jbtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtSalir.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jbtSalir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbtSalir.setMaximumSize(new java.awt.Dimension(30, 36));
        jbtSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/&IconButtons/Salir2.png"))); // NOI18N
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        jRadioButtonMateriasInscriptas.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRadioButtonMateriasInscriptas.setForeground(new java.awt.Color(51, 255, 153));
        jRadioButtonMateriasInscriptas.setText("Materias inscriptas");
        jRadioButtonMateriasInscriptas.setContentAreaFilled(false);
        jRadioButtonMateriasInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMateriasInscriptasActionPerformed(evt);
            }
        });

        jRadioButtonMateriasNoInscriptas.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRadioButtonMateriasNoInscriptas.setForeground(new java.awt.Color(102, 0, 51));
        jRadioButtonMateriasNoInscriptas.setText("Materias no inscriptas");
        jRadioButtonMateriasNoInscriptas.setContentAreaFilled(false);
        jRadioButtonMateriasNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMateriasNoInscriptasActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(153, 153, 255));
        jTable1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 0, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Año"
            }
        ));
        jTable1.setAlignmentX(7.0F);
        jTable1.setAlignmentY(7.0F);
        jTable1.setGridColor(new java.awt.Color(102, 0, 153));
        jTable1.setSelectionBackground(new java.awt.Color(102, 255, 102));
        jTable1.setSelectionForeground(new java.awt.Color(204, 0, 204));
        jScrollPane3.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleParent(jTable1);

        jComboBListAlum.setBackground(new java.awt.Color(153, 0, 255));
        jComboBListAlum.setForeground(new java.awt.Color(255, 255, 255));
        jComboBListAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBListAlumActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/&Images/logo-universidad-de-la-punta.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jbtInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtAnularInscripcion)
                                .addGap(27, 27, 27)
                                .addComponent(jbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jRadioButtonMateriasInscriptas)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonMateriasNoInscriptas)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBListAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBListAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMateriasInscriptas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonMateriasNoInscriptas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtAnularInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jbtInscribir.getAccessibleContext().setAccessibleParent(jbtInscribir);
        jbtSalir.getAccessibleContext().setAccessibleName("jbtSalir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMateriasInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMateriasInscriptasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMateriasInscriptasActionPerformed

    private void jbtInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtInscribirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtInscribirActionPerformed

    private void jComboBListAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBListAlumActionPerformed
        //        Alumno alumnoSeleccionado = (Alumno) jComboBListAlum.getSelectedItem();
        //        jTCargaNotas
    }//GEN-LAST:event_jComboBListAlumActionPerformed

    private void jRadioButtonMateriasNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMateriasNoInscriptasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMateriasNoInscriptasActionPerformed

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtSalirActionPerformed
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JComboBox jComboBListAlum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButton jRadioButtonMateriasInscriptas;
    public javax.swing.JRadioButton jRadioButtonMateriasNoInscriptas;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1;
    public javax.swing.JButton jbtAnularInscripcion;
    public javax.swing.JButton jbtInscribir;
    public javax.swing.JButton jbtSalir;
    // End of variables declaration//GEN-END:variables

    private void inscribirAlumn() {
        Inscripciones.addColumn("id");
        Inscripciones.addColumn("Nombre");
        Inscripciones.addColumn("año");
        //  Inscripciones.setModelo(modelo);

    }
}
